### PR TITLE
fix: shell syntax error #39

### LINKED ISSUE #39: when externalStorage.createDatabase=true, apiserver-deployment.yaml init-container SQL syntax error
### What happened?

❯ 
apiserver中init-container 运行失败！日志如下：
kubectl logs -n clusterpedia-system clusterpedia-apiserver-699d9b997c-rf7wx -c ensure-database
mysql: Can't get stat of '/opt/bitnami/mysql/conf/bitnami/my_custom.cnf' (OS errno 2 - No such file or directory)
mysql: [ERROR] Stopped processing the 'include' directive in file /opt/bitnami/mysql/conf/my.cnf at line 30.
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '{database}' at line 1
waiting for database check

检查apiserver-deployment.yaml中init-container. command 发现是由于单引号导致${database}没有被转移导致无法引用正确的数据库名称。

### What did you expect to happen?

修改apiserver-deployment.yaml 中 init-container. command内容，修改逻辑可以参考clustersynchro-manager-deployment.yaml文件

### How can we reproduce it (as minimally and precisely as possible)?

 当设置.Values.externalStorage.createDatabase=true时，无法成功运行apiserver。

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by yyzxw**
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

fix #39 
image

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/clusterpedia-io/clusterpedia-helm/blob/main/CONTRIBUTING.md#versioning)
* [ ] I have updated the documentation according to [documentation](https://github.com/clusterpedia-io/clusterpedia-helm/blob/main/CONTRIBUTING.md#documentation)
* [ ] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/clusterpedia-io/clusterpedia-helm/blob/main/CONTRIBUTING.md).

Changes are automatically published when merged to `main`. They are not published on branches.

### CODE REVIEW

**Review by Iceber — APPROVED** [review]
LGTM

**Comment by calvin0327** [comment]
LGTM

**Comment by calvin0327** [comment]
@yyzxw pls bump the chart version, reference: https://github.com/clusterpedia-io/clusterpedia-helm/blob/main/CONTRIBUTING.md#versioning

**Comment by Iceber** [comment]
@yyzxw Thanks for your contribution

**Comment by Iceber** [comment]
@yyzxw commit message and pr title have a typo

> fix: yaml suntax-error
s/suntax/syntax

Also, **this is not a yaml syntax error**, but a shell syntax error, strings wrapped in '' do not parse variables.

**Comment by yyzxw** [comment]
yes, fixed @Iceber

**Pull request merged**
